enable:
  issues: false
  prs: true

labels:
  '✨ feat':
    include:
      - pattern: '^feat:'
        scope: title

  '🐞 fix':
    include:
      - pattern: '^fix:'
        scope: title

  '🔨 refactor':
    include:
      - pattern: '^refactor:'
        scope: title

  '📃 docs':
    include:
      - pattern: '^docs:'
        scope: title

  '⚙️ chore':
    include:
      - pattern: '^chore:'
        scope: title

  '✅ test':
    include:
      - pattern: '^test:'
        scope: title
